#!/bin/bash

NEWENGINE="/tmp/annie"
CURRENTENGINE="$HOME/annie"

BOOK="/usr/local/share/scid/books/Elo2400.bin"
TC="0:30+1"

GAMES=250

PGN="${HOME}/pgn.txt"
CONCURRENT=2

cd ..
make
cp build/annie /tmp/annie

rm -f ${PGN}
cutechess-cli -engine name=New cmd=${NEWENGINE} -engine name=Current cmd=${CURRENTENGINE} -each book=${BOOK} proto=uci tc=${TC} -repeat -rounds $((GAMES/2)) -games 2 -pgnout ${PGN} -concurrency ${CONCURRENT}
