#!/bin/bash

NEWENGINE="$HOME/dev"
CURRENTENGINE="$HOME/prev"
# CURRENTENGINE="$HOME/v11"

BOOK="/usr/local/share/scid/books/Elo2400.bin"
TC="10+1"

GAMES=10000

PGN="${HOME}/pgn.txt"
CONCURRENT=8
# CONCURRENT=1

cd ..
rm -rf build
make
rm ${NEWENGINE}
cp build/amelia ${NEWENGINE}

rm -f ${PGN}

# cutechess-cli -engine name=New cmd=${NEWENGINE} -engine name=Current cmd=${CURRENTENGINE} -each book=${BOOK} restart=on proto=uci tc=${TC} -repeat -rounds $((GAMES/2)) -games 2 -pgnout ${PGN} -concurrency ${CONCURRENT} -ratinginterval 2 -sprt elo0=0 elo1=10 alpha=0.05 beta=0.05 -recover -debug
cutechess-cli -engine name=New cmd=${NEWENGINE} -engine name=Current cmd=${CURRENTENGINE} -each book=${BOOK} restart=on proto=uci tc=${TC} -repeat -rounds $((GAMES/2)) -games 2 -pgnout ${PGN} -concurrency ${CONCURRENT} -ratinginterval 2 -sprt elo0=0 elo1=10 alpha=0.05 beta=0.05 -recover
